version: '3.4'

services:
  cloud:
    image: cloud
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cloud?userUnicode=true&characterEncoding=UtF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_REDIS_HOST=redis
    volumes:
      - cloud_data:/cloud_data
    depends_on:
      - mysql
      - redis
    ports:
      - 8081:8081
  
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: cloud
    volumes:
      - ./cloud_server.sql:/docker-entrypoint-initdb.d/cloud_server.sql
      - mysql_data:/var/lib/mysql
  
  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  cloud_data:
  mysql_data:
  redis_data: